//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public long PedidoID { get; set; }
        public long Cliente { get; set; }
        public long Empleado { get; set; }
        public string FechaEntrega { get; set; }
        public Nullable<long> Entregado { get; set; }
    
        public virtual Cliente Cliente1 { get; set; }
        public virtual Empleado Empleado1 { get; set; }
    }
}
